print("This is the Template for Self Introduction!!")
print("\n")
print("Please Enter the Details as per the Instructions.")
print("\n")
print("Enjoy the automation.")
print("\n")
name = input("Please Enter Your Name and Surname: ")
print("\n")
place = input("Enter Your Native Place: ")
print("\n")
Degree = input("Enter Your Type of Degree: ")
print("\n")
stream = input("Enter Your Stream/Branch: ")
print("\n")
gradYear = input("Enter the year of completion: ")
print("\n")
clgName = input("Enter Your College Name: ")
print("\n")
courseNH = input("Please Enter the course name Enrolled in NH: ")
print("\n")
print("My name is "+name+". I am from "+place+" .I  have  Recentely Completed My "+Degree+" in "+stream+" from "+clgName+" in the year of "+gradYear+".I Enrolled "+courseNH+" Course in Networkers Home.")